export class StudentdataInterface {
    id: number
    std_acc_id: number
    std_id: number
    std_prefixth: string
    std_firstname_th: string
    std_lastname_th: string
    std_prefixen: string
    std_firstname_en: string
    std_lastname_en: string
    std_hr_prepare: number
    std_hr_conference: number
    std_yesr: number
    std_passed_credit: string
    std_gpax: string
    std_course: string
    std_branch: string
    std_house_particulars_address: string
    std_now_address: string
    std_tel: string
    std_mobile_tel: string
    std_email: string
    std_parent_first_name: string
    std_parent_last_name: string
    std_parent_relation: string
    std_parent_address: string
    std_parent_mobile: string
    std_parent_tel: string
    std_parent_email: string
}